/* Copyright Statement:
*This firmware are protected under relevant copyright laws,this information contained
*herein is confidential and proprietary to Goodix.
*
* Copyright  (C)  2010 - 2017 Goodix. Ltd.
*
*WARNING:The GTP_COMPATIBLE_MODE part of this file was generated by the specialized tools,
*please do not modify it manually!
*
*/

#ifndef _GT9XX_FIRMWARE_H_
#define _GT9XX_FIRMWARE_H_

//#define GT9XX_FW_HEAD_FILE 1
unsigned char gt9xx_fw_data[] =
{
};
#endif

